# Ultralytics YOLO ðŸš€, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.4  # threshold for the first association
track_low_thresh: 0.1  # threshold for the second association
new_track_thresh: 0.1  # threshold for init new track if the detection does not match any tracks
track_buffer: 300  # buffer to calculate the time when to remove tracks
match_thresh: 0.8  # threshold for matching tracks
alpha: 0.9
non_maximum_iou_distance: 0.15
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow  # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False

# tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
# track_high_thresh: 0.33824964456239337 # threshold for the first association
# track_low_thresh: 0.1  # threshold for the second association
# new_track_thresh: 0.21144301345190655  # threshold for init new track if the detection does not match any tracks
# track_buffer: 60  # buffer to calculate the time when to remove tracks
# match_thresh: 0.22734550911325851  # threshold for matching tracks
# alpha: 0.9
# non_maximum_iou_distance: 0.15
# # min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# # mot20: False  # for tracker evaluation(not used for now)

# # BoT-SORT settings
# gmc_method: sparseOptFlow  # method of global motion compensation
# # ReID model related thresh (not supported yet)
# proximity_thresh: 0.5
# appearance_thresh: 0.4818211117541298
# with_reid: False